### ISSUE TITLE
Error displaying UTF-8 characters in comments

### ISSUE THREAD

**Issue by narutolee** [uber/phabricator-jenkins-plugin#101]
After my Jenkins posts the content of .phabricator-comment to my phabricator instance, the chinese characters will all change to "?".

I doubt I should change
      "UrlEncodedFormEntity entity = new UrlEncodedFormEntity(formData);"
to
      "UrlEncodedFormEntity entity = new UrlEncodedFormEntity(formData, "UTF-8");"

I imported the project with "Existing Maven Projects" in eclipse and modifed the code.
But, there was a problem with maven-checkstyle-plugin2.15.

I use a rough method. I comment all the test code. I replace "@Test" with "//@Test", then use "mvn package" to generate hpi.

But my plugin cannot appear in the job configration webpage.
Please forgive me for my being unfamiliar with java and maven.

**Comment by sectioneight** [comment]
Can you post the problematic ".phabricator-comment" file (or a redacted version of it) so that I can attempt to reproduce?

**Comment by narutolee** [comment]
content of ".phabricator-comment" file like this

第5次构建

It means “buildable 5”.

**Comment by sectioneight** [comment]
Thanks. Do you have an associated stacktrace? I just added a test case with some UTF-8 data in there and it passed, which leads me to believe the UrlEncodedFormEntity is not the issue.

**Comment by narutolee** [comment]
I am a rookie, a new programmer. I have no   associated stacktrace. Sorry, ha-ha.

**Comment by sectioneight** [comment]
Oh, I see, you're not encountering a *crash*, you're just not seeing the characters displaying properly. I have a fix for this.

**Comment by narutolee** [comment]
Yes, thank you so much.

**Comment by sectioneight** [comment]
It's past the workday on the West Coast, so I'll get this reviewed and merged tomorrow, then cut a new 1.8.1 release.

**Comment by sectioneight** [comment]
In the meantime, you can pull down the branch for #102 and run `mvn hpi:package` and get a `.hpi` package if you'd like to install this patch before the new version is out.

**Comment by narutolee** [comment]
Thank you so much! ^_^
