### ISSUE TITLE
Apply dependent revisions successively

### ISSUE THREAD

**Issue by ChaitanyaPramod** [uber/phabricator-jenkins-plugin#104]
Currently, even if revision 456 is dependant on revision 123, the plugin tries to apply 456 on master and fails often. It'd be useful if it could apply the diffs from depending revisions first.

**Comment by sectioneight** [comment]
Have you looked into "staging areas"? I believe this would solve your issue.

**Comment by ChaitanyaPramod** [comment]
I have recently realized that [arcanist] [arc_help] patches the dependant revisions by itself. That solves my issue partially. Once #115 is closed, this can be too. :grinning: 

[arc_help]: https://github.com/phacility/arcanist/blob/master/src/workflow/ArcanistPatchWorkflow.php#L92
