### ISSUE TITLE
Conduit unable to fetch differential

### ISSUE THREAD

**Issue by pdilyard** [uber/phabricator-jenkins-plugin#113]
I've followed [the instructions here](https://wiki.jenkins-ci.org/display/JENKINS/Phabricator+Differential+Plugin) to a tee, but when the Jenkins build finishes successfully, the build status in Harbormaster is never updated. I'm getting this message at the end of the Jenkins build console:
```
[phabricator:uberalls] No cobertura results found
[phabricator:conduit] Unable to fetch differential
Finished: SUCCESS
```
I've tried configuring conduit API keys multiple times, so I'm not sure what's going on here.

Any help would be appreciated.

**Comment by sectioneight** [comment]
What is the URL you've entered for the credentials? Does the key work with a `arc call-conduit`?

e.g.

```
echo '{}' | arc call-conduit user.whoami --conduit-token=<token>
```

**Comment by pdilyard** [comment]
I've definitely entered the correct URL for the credentials...e.g. "phab.example.com". The result of running that command on my Jenkins server was:
```
{
  "error": null,
  "errorMessage": null,
  "response": {
    "phid": "PHID-USER-redacted",
    "userName": "jenkins",
    "realName": "Jenkins",
    "image": "http://phab.redacted.com/res/1444794764T/phabricator/3eb28cd9/rsrc/image/avatar.png",
    "uri": "http://phab.redacted.com/p/jenkins/",
    "roles": [
      "agent",
      "verified",
      "approved",
      "activated"
    ],
    "primaryEmail": "jenkins@redacted.com"
  }
}
```

**Comment by sectioneight** [comment]
For the credentials, is it fully-qualified, e.g. "http://phab.example.com", or just the raw "phab.example.com"?

**Comment by sectioneight** [comment]
If that's not it, probably easiest to hop on a quick google hangout to do a screen share? I can find some time on Monday.

**Comment by pdilyard** [comment]
Fully qualified.

Also to note, the parameters coming through to Jenkins are the following:
```
PHID: PHID-HMBT-3ipgtoqotptkhpglmixb
DIFF_ID: 12
```
I tried manually calling `harbormaster.sendmessage` with curl with those parameters, but I get an error "No such build target!"

**Comment by sectioneight** [comment]
Lame. Can you send me an email at `ai` at `uber` dot `com` if you want to set up a quick debugging session? These issues can be pretty hard to troubleshoot over GitHub.

**Comment by pdilyard** [comment]
Sure, thank you!

**Comment by sectioneight** [comment]
Based on video chat, seems to be a permissioning issue with the jenkins bot user. Closing for now, please re-open if you're still having issues after granting your jenkins bot the proper access.

**Comment by sectioneight** [comment]
Turns out it was a token issue. Updated logging to be more verbose and will clean up install instructions to be more explicit.
