### ISSUE TITLE
Allow diffs to be applied even when the base commit isn't found

### ISSUE THREAD

**Issue by ChaitanyaPramod** [uber/phabricator-jenkins-plugin#115]
Log snippet of one such issue:
```
[workspace] $ /var/lib/arc/arcanist/bin/arc patch --diff 14616 --nobranch ********


    This diff is against commit c54a041bd3fd117c55101093a1334d9c67de53d3, but
    the commit is nowhere in the working copy. Try to apply it against the
    current working copy state? (583466119699885a29c0fde01242c045a89e693b)
    [Y/n] 49Exception
The program is attempting to read user input, but stdin is being piped from some other source (not a TTY).
(Run with `--trace` for a full exception trace.)
[phabricator:arcanist] Error applying arc patch; got non-zero exit code FAILURE
```

It'd be useful to let the plugin continue to apply the diff. If this behaviour is not generally accepted, then it could be behind a config preference.

**Comment by ChaitanyaPramod** [comment]
I'm not sure if this is a proper solution, but running `arc patch` with `--force` works for my case

**Comment by sectioneight** [comment]
If that's all it takes (and the patch succeeds with --force and gives you
what you want to test), making it an optional checkbox sounds reasonable.

**Comment by sectioneight** [comment]
Sorry, to be clear, that was a question -- does the `--force` option complete successfully and leave you with a working copy where your tests can be run?

**Comment by ChaitanyaPramod** [comment]
Yes, the `--force` option completes successfully in my cases, and fails when the patch(es) couldn't be cleanly applied (as desired).

Closing this will also close my other issue - #104 as well.

**Comment by ChaitanyaPramod** [comment]
If I can get some help, I can submit a PR too.

**Comment by ChaitanyaPramod** [comment]
I took a stab at it in #116. Requesting review, @sectioneight.

**Comment by sectioneight** [comment]
Thanks for the PR. Merged.
