### ISSUE TITLE
Adding URL artefact to build before CI finishes build

### ISSUE THREAD

**Issue by ChaitanyaPramod** [uber/phabricator-jenkins-plugin#133]
Context: Our builds are sometimes long (order of minutes). It'll be useful to see the Jenkins build job link in Phabricator as soon the build is started (as opposed to the link being added at the end of the build job).

Do you guys think if Phabricator allows this with their Harbormaster APIs?

**Comment by Hunsu** [comment]
I don't think that Harbormaster allow this. It just wait for pass or fail message.

**Comment by sectioneight** [comment]
I haven't tested this but the "harbormaster.createartifact" message (which
sets the URL) should be callable at any point in the build lifecycle (as
opposed to .sendmessage which sets the pass/fail).

I've been meaning to do this for a while. See #94

**Comment by sectioneight** [comment]
For now though, you can enable the "show build started message" which
leaves the link in a comment as soon as Jenkins starts your build.
