### ISSUE TITLE
Phabricator-Jenkins plugin issue; Jenkins builds generate no artifacts 

### ISSUE THREAD

**Issue by dbeachler** [uber/phabricator-jenkins-plugin#141]
I finally have Phabricator and Jenkins integrated.  However, when I kick off a build in either Phabricator or Jenkins, there are no results.  There are archived .jar files when I kicked off a build of Java code.  I did try to configure Jenkins with post-build actions to "archive the artifacts."  That however causes the builds to fail because there are no artifacts.  I am doing a parameterized build. The builds pass, but nothing is generated.

**Comment by sectioneight** [comment]
Can you paste the build log? What exactly do you mean by "there are no results"? It's not clear based on this report whether this is an issue with your jenkins job configuration, your repository under test, or something to do with the Phabricator integration.

**Comment by dbeachler** [comment]
In Jenkins, the build output is: 

Building in workspace /var/lib/jenkins/jobs/DansItem/workspace
[phabricator:ignore-build] No differential ID found.
[phabricator:plugin-provider] 'cobertura' plugin not installed.
[phabricator:non-differential-harbormaster] Sending diffusion result as: SUCCESS
Finished: SUCCESS

There is nothing in the workspace for that build.  Looking at Jenkins documentation, building Java code should result in some .jar .war files. My Jenkins build creates nothing.
In Phabricator, there is an artifact tab, that is just a link back to Jenkins:

![phabricator capture](https://cloud.githubusercontent.com/assets/16101918/13583204/0e4ce2b4-e47e-11e5-8d90-d167b15d44e9.PNG)

**Comment by sectioneight** [comment]
OK, I think I understand this issue. You are building artifacts in jenkins (jars/wars) and have your jenkins job configured to save your artifacts. You're *also* expecting those artifacts to show up in Phabricator under the "Artifacts" tab.

That is not currently supported. It's probably something we can add, but Artifacts are a relatively recent addition to Phabricator and we currently are only using them to publish the build link.

Other than missing your jars/wars in Phabricator, are you having other issues?

**Comment by dbeachler** [comment]
I am kicking off a build in Phabricator, which also starts one in Jenkins. The build executes successfully, but as I understand it there should be something generated as a result of that build (jars/wars). My issue is that is not happening at all. As I understand it, Jenkins should generate some artifact after a successful build.  However, there are no artifacts showing up in Jenkins:
![jenkinscapture](https://cloud.githubusercontent.com/assets/16101918/13602068/3c14723c-e502-11e5-85bb-a764852b2f4b.PNG)

**Comment by sectioneight** [comment]
Ah, I understand your issue. This actually has nothing to do with Phabricator or this plugin.

You need to add a post-build action to "archive the artifacts":

![image](https://cloud.githubusercontent.com/assets/97087/13607099/85ea58e4-e503-11e5-84b6-d9bf2cd11474.png)

![image](https://cloud.githubusercontent.com/assets/97087/13607108/8ccdcea2-e503-11e5-8290-dbd2735a6a8f.png)

Basically you give it a path (you can use `*` and `**` for wildcards and recursive wildcards respectively)

**Comment by dbeachler** [comment]
I have tried that. Whenever I set a post build action, the build fails. I have tried just setting a single wildcard (*) character, and the job fails saying there are no artifacts found.
![jenkinscapture5 png](https://cloud.githubusercontent.com/assets/16101918/13610997/4fbe1456-e52e-11e5-8825-0295473ccc54.PNG)

**Comment by sectioneight** [comment]
I think you need to be more specific than just the wildcard. What is the path of the file you are trying to artifact? For example, a common one is `target/**/*.jar`

**Comment by dbeachler** [comment]
It doesn't seem to matter what I put there. The job fails regardless.
![jenkinscapture6 png](https://cloud.githubusercontent.com/assets/16101918/13611978/2ac0ba96-e533-11e5-8330-d48cc3b04af6.PNG)
![jenkinscapture7 png](https://cloud.githubusercontent.com/assets/16101918/13611975/2a987d6a-e533-11e5-80ab-91e62e64c794.PNG)
![jenkinscapture9 png](https://cloud.githubusercontent.com/assets/16101918/13612038/70f59482-e533-11e5-850c-ffd419696298.PNG)
![jenkinscapture8 png](https://cloud.githubusercontent.com/assets/16101918/13611976/2a9c42e2-e533-11e5-8ee3-1639d93f7982.PNG)
![jenkinscapture10 png](https://cloud.githubusercontent.com/assets/16101918/13612111/caf2e142-e533-11e5-93fc-319729341ebc.PNG)

**Comment by sectioneight** [comment]
I would try in #jenkins on IRC. I don't use Jenkins artifacts and don't
have any experience debugging these issues (which seem to be unrelated to
Phabricator or this plugin).

**Comment by dbeachler** [comment]
Ok, thanks for the help.  I appreciate the effort.

**Comment by dbeachler** [comment]
Can I get your thoughts on the issue?  I am beginning to think that since the build was kicked off in Phabricator, there are no artifacts for Jenkins to generate and archive.  Could that be the case?

**Comment by sectioneight** [comment]
I can't see how the build is triggered would have anything to do with the artifacts created.

Try this:

Create a new job with a build script that just does "mkdir target && touch target/test.jar". Then try to set your artifacts to archive `target/*.jar` and see if it works.
