### ISSUE TITLE
Collapse multiple pending builds for one revision

### ISSUE THREAD

**Issue by ChaitanyaPramod** [uber/phabricator-jenkins-plugin#144]
[Close if out of plugin's scope]

I'm looking for guidance/help in achieving this for now. (Cooler if the plugin provides an option :wink:)

If there are multiple queued Jenkins builds corresponding to multiple updates on a revision, how can the builds be collapsed to build only the latest build of a revision?

**Comment by sectioneight** [comment]
This has something we've been investigating internally as well. @Ignas did we ever find something that works here?

**Comment by kageiit** [comment]
While a job is in the queue, the plugin does not have any hooks for it to process and trim the queue. The only other way I can think of is to have running builds take a look at the queue during the plugin execution phases and try to optimize the queue, but I believe that will lead to weird results. If you have too mNy items wait in queue, it might help to bump up the executors instead and let #171 take care of it when new jobs are executed

**Comment by ChaitanyaPramod** [comment]
Our builds are CPU intensive on a small machine, so increasing the number of executors is not tenable for us (as the builds could be of different revisions).

A plugin does seem to have hooks into queue

1. One thread to explore is via Jenkins Extensions. [QueueListener](https://wiki.jenkins-ci.org/display/JENKINS/Extension+points#Extensionpoints-hudson.model.queue.QueueListener) seems interesting
2. GHPRB plugin (which offers similar capabilities for Github-Jenkins integration) seems to have a similar feature in https://github.com/jenkinsci/ghprb-plugin/pull/273 (which also seems to be using Jenkins Extensions in some form, perhaps custom extension points)

**Comment by ChaitanyaPramod** [comment]
Another simpler way could be this:
The build task [gets the queue](http://javadoc.jenkins-ci.org/jenkins/model/Jenkins.html#getQueue--) and aborts itself if it finds a newer build scheduled.

**Comment by sectioneight** [comment]
I believe this was implemented in #171

**Comment by ChaitanyaPramod** [comment]
> I believe this was implemented in #171

Not completely. The builds in queue aren't touched. Typical Jenkins installations have limited number of executors and an infinite queue. See [comment on the PR](https://github.com/uber/phabricator-jenkins-plugin/pull/171#issuecomment-240316574).
