### ISSUE TITLE
java.io.IOException: Cannot run program "arc"

### ISSUE THREAD

**Issue by adolf2v** [uber/phabricator-jenkins-plugin#145]
the below is the error message:
```
[api_build_job] $ arc patch --diff 10811 --nocommit --nobranch ********
java.io.IOException: Cannot run program "arc" (in directory "/root/.jenkins/workspace/api_build_job"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at hudson.Proc$LocalProc.<init>(Proc.java:244)
	at hudson.Proc$LocalProc.<init>(Proc.java:216)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:815)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.Launcher$ProcStarter.join(Launcher.java:388)
	at com.uber.jenkins.phabricator.conduit.ArcanistClient.callConduit(ArcanistClient.java:59)
	at com.uber.jenkins.phabricator.tasks.ApplyPatchTask.execute(ApplyPatchTask.java:129)
	at com.uber.jenkins.phabricator.tasks.Task.run(Task.java:58)
	at com.uber.jenkins.phabricator.PhabricatorBuildWrapper.setUp(PhabricatorBuildWrapper.java:151)
	at hudson.model.Build$BuildExecution.doRun(Build.java:156)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 15 more
[phabricator:arcanist] Error applying arc patch; got non-zero exit code FAILURE
```

I have arcanist in the host,and can run arc command,also add the path of arc to the PATH.
In the job's directory ,i can run the arc command.

**Comment by sectioneight** [comment]
It sounds like you've configured jenkins to point to an `arc` path that doesn't have an `arc` binary. What does your configuration point to? Do you have the `arc` binary installed on your jenkins slave nodes, or just the master? What path is it in?

**Comment by adolf2v** [comment]
I have the arc binary installed，and can run  the arc command in the jenkins' workspace。
In the global configuration of jenkins ，using the absolute Path of arc
 (Location of arcanist ) can solve this problem.

Thanks a lot

**Comment by sectioneight** [comment]
Ok, it sounds like this issue is resolved, I'll close out. Yes, if you install the `arc` binary somewhere that is not in the jenkins' user's path, you need to specify the path in the global config.

**Comment by YechengZhou** [comment]
Hi, I met the same problem,:
`[pha_wave_driver_android_build] $ arc patch --diff 11164 --nocommit ********
java.io.IOException: Cannot run program "arc" (in directory "/Users/xxx/jenkins/workspace/pha_wave_driver_android_build"): error=2, No such file or directory`
But I run arc command in "Execute Shell" block.

**Comment by sectioneight** [comment]
Do you have the arc binary installed? What path is it in? Did you set a
custom path in your global configuration? As much information as possible
is usually a good start to debug things like this.

**Comment by YechengZhou** [comment]
yes, I have arc binary installed and the path is /Users/xx/CRClientTools/arcanist/bin/arc and it is already in PATH, I can run arc on both Linux command line and "Execute Shell" block in jenkins job step setting.

**Comment by YechengZhou** [comment]
Sorry, after config arc path in global config, it works.

**Comment by sectioneight** [comment]
Ok, cool, I'll leave this closed out then. Let me know if you run into any other issues.

**Comment by nunohorta** [comment]
this is happening to me but my project is running on a slave. If I ssh into the slave and try to use arc it works fine. Do I also need to have arc on the jenkins server?

**Comment by sectioneight** [comment]
Have you configured the path properly? arc should not be necessary on the
master

**Comment by nunohorta** [comment]
yeah I set an environment variable PATH for the slave. I restarted it and I can see the path updated under Node > System Information > Environment variables but it's still not working. Also if I go to the script console on that slave and run println System.getenv("PATH") the output is different from the environment variable

**Comment by sectioneight** [comment]
Can you try configuring your global Phabricator options with the absolute
path to "arc"? That way it won't depend on environment variables

**Comment by nunohorta** [comment]
it's still throwing the same error. The slave is running osx, I'm not sure if that helps

**Comment by sectioneight** [comment]
What does your global configuration look like? What path is arc installed
to so your OS X machines?

**Comment by nunohorta** [comment]
![screen shot 2016-06-02 at 09 09 21](https://cloud.githubusercontent.com/assets/1571425/15738129/c30c943a-28a1-11e6-8cc4-a928b6acd062.png)

That's what I added to the global configuration and to the slave. I can see the same path if I go to the slave "System Information". "build" is the name of the user that I setup to launch the slave agent via ssh

**Comment by reidmain** [comment]
Which PATH environment variable does the plugin use by default?

It seems that the plugin is not sourcing the .bash_profile of our jenkins user before running because the `arc` command is in the PATH specified there. I can run `arc` from both Terminal.app when I am logged in as the jenkins user and from the "Execute Shell" block in Jenkins.

I could hardcode the location of arcanist but I am in the process of migrating our nodes to a new configuration where the arcanist location will differ than the old nodes. Rather than upgrade them all at once I was hoping I could provisioning the new nodes to put arcanist in the correct location and once they were all up and running go back to the old nodes and fix them.
