### ISSUE TITLE
Adding other linting metrics into the .phabricator-comment

### ISSUE THREAD

**Issue by steveworkman** [uber/phabricator-jenkins-plugin#146]
I'm trying to set up the phabricator comment to provide more useful information back to Phabricator that it doesn't normally get, such as:

> 
> Build is green
> 
> This build has $CHECKSTYLE_COUNT warnings of which $CHECKSTYLE_NEW are new and $CHECKSTYLE_FIXED were fixed in this build

However, these variables (which should be environment variables that were set) aren't present. Is there any documentation on how to do this?

**Comment by sectioneight** [comment]
I see, are you checking in this `.phabricator-comment` file to your repo? Instead, you should create it as part of the build step, since it's just copied as plain text by the plugin (no variable expansion).

For example, your build script could be:

```
#!/bin/bash
set -ex

# run your tests here...
echo "The build has $CHECKSTYLE_COUNT..." > .phabricator-comment
```

**Comment by steveworkman** [comment]
Right, that makes more sense. Seems the variables aren't being populated for me but at least they're getting replaced. Thanks
