### ISSUE TITLE
Add support to send unit/coverage data only for affected files in the diff

### ISSUE THREAD

**Issue by kageiit** [uber/phabricator-jenkins-plugin#147]
Currently HarbormasterResult contains unit results and coverage of all files which is wasteful in some cases. Provide an option to only send data for changed files

**Comment by sectioneight** [comment]
Makes sense but... how do we know based on unit/coverage data which results have to do with changed files?

**Comment by kageiit** [comment]
its possible by analyzing the filename attribute in code coverage xmls. I will open a PR for this

**Comment by kageiit** [comment]
The changed files data is already available for builds that have a diff object associated with them. we just need to match and filter out. conduit.querydiffs already gives us that info, we currently discard it
