### ISSUE TITLE
Building with revision dependencies

### ISSUE THREAD

**Issue by adamchainz** [uber/phabricator-jenkins-plugin#157]
`arc patch help` implies that running it on a revision that depends on another should bring in the latest diff from the other, but it doesn't seem to do that.

To support revision-on-revision testing, would it be easy to make the plugin pull in dependency revisions, or would it be better to make `arc patch` to do that?

**Comment by sectioneight** [comment]
Potential duplicate of #104

We make this work at Uber by using "Staging Areas" which ensure that the dependent branch/revision is available to apply the patch to. It sounds like `arc` should be intelligent enough to do this for you -- is it not? Do you have some build logs of what happens when you try to use the plugin to do this?

**Comment by adamchainz** [comment]
Sorry for no reply, I just got around to trying this. Staging area seems to work, although as the [harbormaster docs note](https://secure.phabricator.com/book/phabricator/article/harbormaster/) they're apparently quite experimental.

One thing I found is that the "Create git branch" flag is required in the plugin for the staging area to work.

I think the README could be updated to mention staging areas.

**Comment by sectioneight** [comment]
Yup, I've been holding off on recommending that until it comes out of "experimental" phase, but it's probably time to document it and just put a big fat warning that it's subject to change and not officially supported on the Phabricator side.

**Comment by adamchainz** [comment]
Btw do you have a process for removing the staging area tags? Because I've noticed harbormaster doesn't seem to care about removing them at any point

**Comment by sectioneight** [comment]
Nope. I assume Phabricator will provide a way to prune them at some point.

**Comment by kageiit** [comment]
> Btw do you have a process for removing the staging area tags

We setup a jenkins job to automatically purge tags older than a week and it runs once a week on the repos on which we have staging areas configured

**Comment by adamchainz** [comment]
> We setup a jenkins job to automatically purge tags older than a week and it runs once a week on the repos on which we have staging areas configured

Sweet. Got a bash one liner you can share? 😸

**Comment by kageiit** [comment]
> Sweet. Got a bash one liner you can share? 😸

I dont think its a one liner. It involves some logic which talks to phab api and uses some other git commands to get staging area refs within a timeframe and deletes them.

**Comment by adamchainz** [comment]
Oh okay fair.

**Comment by sectioneight** [comment]
@adamchainz @kageiit is there something to be done here from the plugin side? Seems like this is a phabricator/tag cruft thing that we don't have any control over. If there's something we can implement, please re-open and let me know.

**Comment by adamchainz** [comment]
Maybe document the potential for staging areas, despite their 'experimental' status?

**Comment by sectioneight** [comment]
Good call, will overhaul docs in #154
