### ISSUE TITLE
no protocol error 

### ISSUE THREAD

**Issue by xecutioner** [uber/phabricator-jenkins-plugin#158]
I am trying to set up a CI with jenkins and integrate with phabricator. I've followed blindly with the instructions given in the readme However, 
I'm having this exception in jenkins log. Please advise  

> Building in workspace /var/lib/jenkins/workspace/designerex
> [phabricator:harbormaster] Sending Harbormaster BUILD_URL via PHID: PHID-HMBT-nzbv4klynwc3gamewhyw
> [phabricator:harbormaster] Unable to send BUILD_URL to Harbormaster
> com.uber.jenkins.phabricator.conduit.ConduitAPIException: no protocol: phabricator.jyaasa.com
> 	at com.uber.jenkins.phabricator.conduit.ConduitAPIClient.createRequest(ConduitAPIClient.java:101)
> 	at com.uber.jenkins.phabricator.conduit.ConduitAPIClient.perform(ConduitAPIClient.java:67)
> 	at com.uber.jenkins.phabricator.conduit.DifferentialClient.callConduit(DifferentialClient.java:147)
> 	at com.uber.jenkins.phabricator.conduit.DifferentialClient.fetchDiff(DifferentialClient.java:70)
> 	at com.uber.jenkins.phabricator.PhabricatorBuildWrapper.setUp(PhabricatorBuildWrapper.java:117)
> 	at hudson.model.Build$BuildExecution.doRun(Build.java:156)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
> 	at hudson.model.Run.execute(Run.java:1741)
> 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
> 	at hudson.model.ResourceController.execute(ResourceController.java:98)
> 	at hudson.model.Executor.run(Executor.java:410)
> [phabricator:conduit] Unable to fetch differential from Conduit API
> [phabricator:conduit] no protocol: phabricator.jyaasa.com
> [phabricator:process-build-result] No line coverage found, skipping...
> [phabricator:process-build-result] No unit results available.
> [phabricator:process-build-result] No coverage provider available.
> [phabricator:harbormaster] Sending Harbormaster BUILD_URL via PHID: PHID-HMBT-nzbv4klynwc3gamewhyw
> [phabricator:process-build-result] Sending build result to Harbormaster with PHID PHID-HMBT-nzbv4klynwc3gamewhyw, success: false
> [phabricator:comment-file] no files found by path: '.phabricator-comment'
> Finished: FAILURE

**Comment by sectioneight** [comment]
It sounds like you're missing a protocol. It should be http://phabricator...
or https://phab... depending on whether you have SSL enabled

**Comment by xecutioner** [comment]
hmm seems so at the first look. what i am wondering us where do i set that
? is it a problem in my plugin set up ? . wierd thing is i have this post
build step where jenkins is posting the build as failed in differential in
phab.
On May 20, 2016 21:38, "Aiden Scandella" <notifications@github.com> wrote:

It sounds like you're missing a protocol. It should be http://phabricator...
or https://phab... depending on whether you have SSL enabled
On Fri, May 20, 2016 at 6:22 AM Kapil Raj Nakhwa <notifications@github.com>
wrote:

> I am trying to set up a CI with jenkins and integrate with phabricator.
> I've followed blindly with the instructions given in the readme However,
> I'm having this exception in jenkins log
>
> Building in workspace /var/lib/jenkins/workspace/designerex
> [phabricator:harbormaster] Sending Harbormaster BUILD_URL via PHID:
> PHID-HMBT-nzbv4klynwc3gamewhyw
> [phabricator:harbormaster] Unable to send BUILD_URL to Harbormaster
> com.uber.jenkins.phabricator.conduit.ConduitAPIException: no protocol:
> phabricator.jyaasa.com
> at
>
com.uber.jenkins.phabricator.conduit.ConduitAPIClient.createRequest(ConduitAPIClient.java:101)
> at
>
com.uber.jenkins.phabricator.conduit.ConduitAPIClient.perform(ConduitAPIClient.java:67)
> at
>
com.uber.jenkins.phabricator.conduit.DifferentialClient.callConduit(DifferentialClient.java:147)
> at
>
com.uber.jenkins.phabricator.conduit.DifferentialClient.fetchDiff(DifferentialClient.java:70)
> at
>
com.uber.jenkins.phabricator.PhabricatorBuildWrapper.setUp(PhabricatorBuildWrapper.java:117)
> at hudson.model.Build$BuildExecution.doRun(Build.java:156)
> at
>
hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
> at hudson.model.Run.execute(Run.java:1741)
> at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
> at hudson.model.ResourceController.execute(ResourceController.java:98)
> at hudson.model.Executor.run(Executor.java:410)
> [phabricator:conduit] Unable to fetch differential from Conduit API
> [phabricator:conduit] no protocol: phabricator.jyaasa.com
> [phabricator:process-build-result] No line coverage found, skipping...
> [phabricator:process-build-result] No unit results available.
> [phabricator:process-build-result] No coverage provider available.
> [phabricator:harbormaster] Sending Harbormaster BUILD_URL via PHID:
> PHID-HMBT-nzbv4klynwc3gamewhyw
> [phabricator:process-build-result] Sending build result to Harbormaster
> with PHID PHID-HMBT-nzbv4klynwc3gamewhyw, success: false
> [phabricator:comment-file] no files found by path: '.phabricator-comment'
> Finished: FAILURE
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/uber/phabricator-jenkins-plugin/issues/158>
>

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/uber/phabricator-jenkins-plugin/issues/158#issuecomment-220644000>

**Comment by sectioneight** [comment]
What do your credentials look like (please don't post your password here).
This is our example:

https://github.com/uber/phabricator-jenkins-plugin/blob/master/docs/configure-credentials.png

Is your "Phabricator URL" a real URL (with the protocol), or is it just the
hostname?

**Comment by xecutioner** [comment]
The problem is that We were missing the protocol (i.e either http or https) while defining the conduit api. 
The problem is resolved.
