### ISSUE TITLE
Jenkins URL is null

### ISSUE THREAD

**Issue by Korri** [uber/phabricator-jenkins-plugin#159]
When my build is successfull I get the following message inside Phabricator:

> Build is green
> ```
> 0 tests failed (out of 461), coverage is 34.54%
> ```
> null for more details.

The center line is my custom message, but I used to have the proper Jenkins URL before upgrading to Jenkins 2, but now I only get `null`

This is the Phabricator plugin output of the build:
```
[phabricator:plugin-provider] 'cobertura' plugin not installed.
[phabricator:process-build-result] No coverage provider available.
[phabricator:harbormaster] Sending Harbormaster BUILD_URL via PHID: PHID-HMBT-zpywrxjycrydvha4gqrt
[phabricator:send-harbormaster-uri] Error from Harbormaster: Missing required parameters: uri
[phabricator:process-build-result] Unable to send BUILD_URL to Harbormaster. This can be safely ignored, and is usually because it's already set.
[phabricator:process-build-result] Publishing unit results to Harbormaster for 461 tests.
[phabricator:process-build-result] Sending build result to Harbormaster with PHID PHID-HMBT-zpywrxjycrydvha4gqrt, success: true
```

**Comment by sectioneight** [comment]
Interesting. I haven't tried Jenkins 2 yet, but it sounds like the way we query for the job URL isn't coming back properly. I'll leave this open until I have time to look at it (heading out for some PTO).

**Comment by Korri** [comment]
Looks like this is not related to the plugin but a Jenkins bug, went into settings, pressed save and it works now.
Here is the issue for Jenkins: https://issues.jenkins-ci.org/browse/JENKINS-28466

**Comment by sectioneight** [comment]
Oh interesting. Thanks for following up!
