### ISSUE TITLE
Add ability to report lint warnings to Phabricator

### ISSUE THREAD

**Issue by ChaitanyaPramod** [uber/phabricator-jenkins-plugin#162]
Like at https://secure.phabricator.com/D14632#5e70abe4

I'm thinking this would work similar to reporting coverage report. Build script would generate an xml/json report locally and then the plugin would parse it and send to Phabricator.

Thoughts?

**Comment by sectioneight** [comment]
Yes, this would definitely be cool.

I'm wondering whether we should just expect users/scripts to output Harbormaster-compatible JSON and send it as-is, or implement our own in-between format that isn't coupled to the harbormaster API (which is beta, and subject to change).

API Reference: https://secure.phabricator.com/conduit/method/harbormaster.sendmessage/ under "Lint Results"

**Comment by clonetwin26** [comment]
This would be a huge win for us, in our android stack :D

**Comment by clonetwin26** [comment]
Really any api that takes a file and line number would be amazing, and do wonders for our static analysis stack.

**Comment by sectioneight** [comment]
Yup, I think the implementation would be pretty easy, it's just a question of:

a) a format to express lint errors
b) a way to configure where jobs should output the lint errors

**Comment by sectioneight** [comment]
@clonetwin26 @ChaitanyaPramod here is the harbormaster format:

```json
[
  {
    "name": "Syntax Error",
    "code": "EXAMPLE1",
    "severity": "error",
    "path": "path/to/example.c",
    "line": 17,
    "char": 3
  },
  {
    "name": "Not A Haiku",
    "code": "EXAMPLE2",
    "severity": "error",
    "path": "path/to/source.cpp",
    "line": 23,
    "char": 1,
    "description": "This function definition is not a haiku."
  }
]
```

Are the lint errors you're trying to report on expressable in that format? Do you have additional metadata that you'd like the plugin to ingest and transform?

**Comment by clonetwin26** [comment]
That should actually work fine. I can adapt my analysis tools to output to this format via this format. Thank you!

**Comment by ChaitanyaPramod** [comment]
Yes, I too am planning to adopt android lint warnings to this format (and also checkstyle and findbugs later).
The android lint tool generates all the required fields for Harbormaster, but in an xml format. We can write an adapter from third party tools' reports to harbormaster format

**Comment by sectioneight** [comment]
Ok, and where are you imagining that adapter living?

Is there some prior art for a tool that processes a variety of lint warnings or some sort of standard we can leverage? Or do we expect our individual test jobs to convert their lint warnings to a Harbormaster format via post-processing? Or should we add ingesters for various lint formats into this plugin?

**Comment by sectioneight** [comment]
I pushed up a branch and started sketching out the boilerplate stuff, but I'm not going to have time to get to this for real for another week or two. If anybody else has the time to implement, feel free.

**Comment by clonetwin26** [comment]
For the android stack I was going to build an android lint gradle plugin that runs the lint tasks, then adapts their output to phabricator. I will call it the lint-phab-plugin.

**Comment by sectioneight** [comment]
Sounds good to me
