### ISSUE TITLE
Plugin reports coverage for 0 files to Phabricator

### ISSUE THREAD

**Issue by ChaitanyaPramod** [uber/phabricator-jenkins-plugin#163]
The xml file is located at `workspace_path/module_name/build/reports/cobertura/coverage.xml`
the `<sources>` element in the xml file points to `workspace_path/module_name/src/main/java` and the class element's filename attribute is (relative to the aforementioned source path) `package_name/ClassName.java`

Everything seems to be in order on Jenkins side, the Cobertura plugin is generating expected reports, however the phabricator plugin prints `[phabricator:process-build-result] Publishing coverage data to Harbormaster for 0 files.` to console (and therefore, Phabricator doesn't show coverage data in diffs)

Note that this proves the `coverageProvider` was not null and `lineCoverage` was not empty in `BuildResultProcessor`.
I have eyeballed `CoberturaCoverageProvider` and `CoberturaXMLParser` but didn't find anything suspicious.
Are there any possible suspects that I should look at?

**Comment by sectioneight** [comment]
Interesting. There's been a fair amount of re-working of coverage processing in recent versions.

Could you provide a repro case? Like a simple tar file with a cobertura XML file and some files where you expect coverage to take effect?

cc @kageiit

**Comment by kageiit** [comment]
I would like to see a repro case as well. as long as paths match, the coverage should be reported correctly. The plugin by default only publishes coverage for changed files in the diff

**Comment by ChaitanyaPramod** [comment]
Have built a simple project to try replicate the issue in a smaller case. It works as expected though (printing `Publishing coverage data to Harbormaster for 1 files.`, though Phabricator doesn't highlight the diff view with coverage data).
I'm closing this issue for now until I figure out why the plugin is unable detect cobertura reports in the main project.
