### ISSUE TITLE
Curious about other folks workflows

### ISSUE THREAD

**Issue by qnm** [uber/phabricator-jenkins-plugin#169]
First - thanks for this plugin, it's very useful.

In the plugin documentation, Phabricator triggers a Jenkins job remotely but needs to pass along `job name` in the URL to allow Jenkins to know which job to trigger.

I have a large-ish number of repos, and ideally I'd like to have one Harbormaster Rule to rule them all.

I see that `callsign` can be passed to Jenkins to indicate the source Repo in Diffusion, however I can't determine what do with that fact, other than perhaps name all my Jenkins jobs after the corresponding callsign.

How do others manage the mapping between Diffusion and Jenkins jobs?

**Comment by sectioneight** [comment]
Good question. @Ignas any thoughts?

**Comment by Hunsu** [comment]
What do you use to launch your build? When I was using Jenkins (now I'm using Drydock) I used to have one script that I use for each job.

**Comment by qnm** [comment]
@Hunsu Currently I'm heading down the 'one HM rule per job' path but it feels like there should be a better way.

**Comment by kageiit** [comment]
One approach that has worked well for us is

- Create a herald rule to trigger on repository projects
- Create one harbormaster rule and pass the repository url in the parameters
- Create one CI job that will checkout the correct repository from the job parameters and build. This is especially easy when you have predefined targets to build. For example on gradle we use `./gradlew build`
- For every new repository on phabricator that needs CI setup, we just add a project tag and immediately get automatic CI support.
