### ISSUE TITLE
Migrate to use Gradle build

### ISSUE THREAD

**Issue by kageiit** [uber/phabricator-jenkins-plugin#173]
https://github.com/jenkinsci/gradle-jpi-plugin
- allows usage of groovy to make plugin code less verbose
- no changes for end consumers
- better testability using groovy meta classes etc

**Comment by sectioneight** [comment]
Sounds good to me. Do you plan on doing this?

**Comment by sectioneight** [comment]
Also how will releases work? Currently we use `mvn release:prepare release:perform`

**Comment by kageiit** [comment]
yes I plan to take this on

**Comment by kageiit** [comment]
All existing flows will still be supported as usual. This gives us ability to hook in other gradle plugins as well for better static analysis i.e more than just code coverage etc.

**Comment by sectioneight** [comment]
dope. thanks dude!
