### ISSUE TITLE
Waiting for Message in phabricator

### ISSUE THREAD

**Issue by rohitranjan1991** [uber/phabricator-jenkins-plugin#177]
I followed the instructions as mentioned in the git page. My jenkins build passes successfully with the end message as 

> [phabricator:process-build-result] Sending build result to Harbormaster with PHID PHID-HMBT-gmbp3r4pqelchj65vup4, success: true

But the phabricato build still shows Waiting for message. Any idea where i am doing wrong.

**Comment by sectioneight** [comment]
Can you post the full build log (or as much as you can)?

**Comment by rohitranjan1991** [comment]
Sure.
`> Started by remote host 52.221.252.201
Building in workspace /var/lib/jenkins/workspace/xyz
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url http://phabricator.example.com/diffusion/8/myawesome.git # timeout=10
Fetching upstream changes from http://phabricator.example.com/diffusion/8/myawesome.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.username BotJenkins # timeout=10
 > git config --local credential.helper store --file=/tmp/git1809409022643892116.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress http://phabricator.example.com/diffusion/8/myawesome.git +refs/heads/*:refs/remotes/origin/*
 > git config --local --remove-section credential # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 0e1d210c50309e89af37ce091ac8266282cd220b (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 0e1d210c50309e89af37ce091ac8266282cd220b
 > git rev-list 0e1d210c50309e89af37ce091ac8266282cd220b # timeout=10
[phabricator:plugin-provider] 'cobertura' plugin not installed.
[phabricator:process-build-result] No unit results available.
[phabricator:process-build-result] No coverage provider available.
[phabricator:harbormaster] Sending Harbormaster BUILD_URL via PHID: PHID-HMBT-gmbp3r4pqelchj65vup4
[phabricator:process-build-result] Sending build result to Harbormaster with PHID PHID-HMBT-gmbp3r4pqelchj65vup4, success: true
Finished: SUCCESS`

**Comment by sectioneight** [comment]
Hmm, it looks like you have a valid PHID setup and it's able to post to Harbormaster properly. Any info on the harbormaster build page for your differential?

**Comment by rohitranjan1991** [comment]
It seems that today when i opened those build there were showing as passed. I wonder why it took so long to process where as it was quick via command line.

**Comment by sectioneight** [comment]
Seems like issue is self-resolved. Please re-open if you have further issues.
