### ISSUE TITLE
"Arc was unable to automagically make a name for this patch. Please clean up your working copy and try again."

### ISSUE THREAD

**Issue by joshma** [uber/phabricator-jenkins-plugin#178]
We're using this plugin with the option to "create git branch" enabled - this results in something like
```
00:00:06.484 [phab-aurelia-js-shard] $ arc patch --diff 22569 --force ********
00:00:07.888 Created and checked out branch arcpatch-D5902.
00:00:10.223 Branch name arcpatch-D5860 already exists; trying a new name.
00:00:10.225 Branch name arcpatch-D5860_1 already exists; trying a new name.
00:00:10.228 Branch name arcpatch-D5860_2 already exists; trying a new name.
00:00:10.242 Branch name arcpatch-D5860_3 already exists; trying a new name.
00:00:10.242 Exception
00:00:10.242 Arc was unable to automagically make a name for this patch. Please clean up your working copy and try again.
00:00:10.242 (Run with `--trace` for a full exception trace.)
```

I'm guessing if you diff more than 4 times on a single workspace, this will happen. Does anyone have ideas for how to configure Jenkins / this plugin to clean up the branches afterwards?

**Comment by sectioneight** [comment]
That's why the flag is off by default. If you'd like to add or request some
branch cleaning behavior id accept a pull request, but it hasn't been a
priority given the workaround.

**Comment by joshma** [comment]
Ah hm, we had turned it on because patching from master leads to really weird behavior for us (since we develop off a `dev` branch). Good to know there isn't something obvious, though.

**Comment by sectioneight** [comment]
You should disable the master flag as well then, in which case it will
patch from the base revision (eg dev in your case).

**Comment by sectioneight** [comment]
Closing due to workaround

**Comment by kageiit** [comment]
This is an issue when trying do perform incremental builds on CI. I will open a PR with the behavior to create a branch with a revisionId_uuid instead of using the revisionId_number

**Comment by kageiit** [comment]
Actually, I think the workaround is fine because the arc patch'ed commit will still stick around despite not having a branch name attached to it.

Will re-open if needed
