### ISSUE TITLE
uberalls client 404

### ISSUE THREAD

**Issue by reilost** [uber/phabricator-jenkins-plugin#179]
when i run a test ,the jenkins output is 
```

[JENKINS] Archiving /var/jenkins_home/workspace/rhllor-coupon/pom.xml to com.ricebook.rhllor/coupon/1.0-SNAPSHOT/coupon-1.0-SNAPSHOT.pom
channel stopped
[phabricator:uberalls-client] Call failed: HTTP/1.1 404 Not Found
[phabricator:uberalls] unable to find coverage for parent commit
[phabricator:process-build-result] No unit results available.
[phabricator:harbormaster] Sending Harbormaster BUILD_URL via PHID: PHID-HMBT-d75u5zgi54dpeqjdcaii
[phabricator:send-harbormaster-uri] Harbormaster declined URI artifact: #1062: Duplicate entry 'uri-r6OsU.f9vK1Y' for key 'key_artifact'
[phabricator:process-build-result] Unable to send BUILD_URL to Harbormaster. This can be safely ignored, and is usually because it's already set.
[phabricator:process-build-result] Publishing coverage data to Harbormaster for 2 files.
[phabricator:process-build-result] Sending build result to Harbormaster with PHID PHID-HMBT-d75u5zgi54dpeqjdcaii, success: true
[phabricator:file-fetcher] no files found by path: '.phabricator-comment'
[Cobertura] Publishing Cobertura coverage report...
Publishing Cobertura coverage results...
Cobertura coverage report found.
Finished: SUCCESS
```

=.=, my uberalls is already run ,what should i do for this error ...

**Comment by sectioneight** [comment]
A 404 is a semantic "coverage not found". It means you have Uberalls configured properly but it's never seen coverage for the commit your diff is branched off of.

Did you follow the instructions at https://github.com/uber/uberalls?

Specifically this part:

> In order to have a baseline to compare against, you must also have jenkins build your project on your mainline branch ("master" by default). You can either create a separate job, or enable SCM polling under Build Triggers:

**Comment by reilost** [comment]
we  enable SCM  =.= ,but still have a 404 
```
[JENKINS] Archiving /var/jenkins_home/workspace/rhllor-coupon/pom.xml to com.ricebook.rhllor/coupon/1.0-SNAPSHOT/coupon-1.0-SNAPSHOT.pom
[phabricator:non-differential] Sending coverage result for 55f687f28e17292e7890aaff867fb187da2f131e as package coverage = 0.0, files coverage = 0.0, classes coverage = 0.0, method coverage = 0.0, line coverage = 0.0, conditional coverage = 0.0
[phabricator:uberalls-client] Call failed: HTTP/1.1 404 Not Found
[Cobertura] Publishing Cobertura coverage report...
Publishing Cobertura coverage results...
Cobertura coverage report found.
Finished: SUCCESS
```

**Comment by sectioneight** [comment]
Sounds like you don't have jenkins configured to point at your uberalls
correctly. You shouldn't be getting a 404 trying to POST data.

What happens if you try to cURL the configured URL from your jenkins master?

**Comment by reilost** [comment]
hmm...
I configured the url is http://10.10.121.176:14740
when i cURL this url is 404
and http://10.10.121.176:14740/health is  `;-)`

**Comment by reilost** [comment]
oh,my mistake 
configured shoud be  http://10.10.121.176:14740/metrics  
Thanks~~~  @sectioneight

**Comment by sectioneight** [comment]
Do you have any more information available?

**Comment by reilost** [comment]
@sectioneight  my mistake, the uberall url should be   http://10.10.121.176:14740/metrics 
my config is only the  http://10.10.121.176:14740
