### ISSUE TITLE
Manage Conduit token within Jenkins UI

### ISSUE THREAD

**Issue by joshuaspence** [uber/phabricator-jenkins-plugin#18]
Currently, this plugin relies on the `~/.arcrc` file. Instead, it would be better to allow the Conduit token to be managed in the Jenkins UI and be passed to arcanist with the `--conduit-token` flag.

**Comment by lavahot** [comment]
This could possibly be done with a jenkins slave setup script, but I agree that this is a much better route.

**Comment by sectioneight** [comment]
Yes, this makes a lot of sense. I'll accept PRs or put it on the backlog for my mythical "free time"
