### ISSUE TITLE
Clean step should clean submodules too

### ISSUE THREAD

**Issue by kavehv** [uber/phabricator-jenkins-plugin#180]
Otherwise the call to arc patch fails with "A submodule has uncommitted or untracked changes"

**Comment by sectioneight** [comment]
I believe you need to configure Jenkins to "Clean after checkout" under additional behaviors -- I don't think this is something we can do from within the Phabricator plugin.

**Comment by kavehv** [comment]
But the phabricator plugin forces a git clean already.  Surely you can add an option to also clean submodules using 'git submodule foreach git clean -fd'

**Comment by sectioneight** [comment]
Sure, but why add a flag to this plugin that's not specific to Phabricator and already available with another option?

**Comment by kavehv** [comment]
Because it's Phabricator that prompts and subsequently causes an error when it tries to apply a patch and there are un-clean submodules that Phabricator complains about.  Because phabricator is doing the complaining, it should take some responsibility in giving the option to clean up the submodule before it complains about it.
