### ISSUE TITLE
The configuration of max lint size isn't being saved

### ISSUE THREAD

**Issue by d-claassen** [uber/phabricator-jenkins-plugin#188]
This is all the config that is saved on my instance:
```
    <com.uber.jenkins.phabricator.PhabricatorNotifier plugin="phabricator-plugin@1.9.7">
      <commentOnSuccess>false</commentOnSuccess>
      <uberallsEnabled>true</uberallsEnabled>
      <commentWithConsoleLinkOnFailure>false</commentWithConsoleLinkOnFailure>
      <preserveFormatting>false</preserveFormatting>
      <commentFile>.phabricator-comment</commentFile>
      <commentSize>1000</commentSize>
      <customComment>false</customComment>
      <processLint>true</processLint>
      <lintFile>.phabricator-lint</lintFile>
    </com.uber.jenkins.phabricator.PhabricatorNotifier>
```

As you can see, there is no `lintSize` or `lintFileSize` saved. So now the max lint file size falls back to the default of 1000 characters max, which are just like 4 or 5 issues.

I'm no Jenkins developer, so I'm not that sure. But it might be related to the usage of `lintSize` in the `config.jelly` file, and the usage of `lintFileSize` in the class `PhabricatorNotifier`.

**Comment by sectioneight** [comment]
Thanks for the report. This is almost certainly a bug in our (my) code. Will prioritize as appropriate.

**Comment by sectioneight** [comment]
cc @jjx just in case you have time to work on this
