### ISSUE TITLE
Duplicate lint errors

### ISSUE THREAD

**Issue by aadis** [uber/phabricator-jenkins-plugin#197]
I have the plugin enabled and am reporting lint errors via .phabricator-lint

However every time a diff is updated, the lint errors are added to the existing ones, duplicating them.

After a few iterations I have 5-7 duplicate lint errors on the files.

Is this expected behaviour?

**Comment by sectioneight** [comment]
Are you wiping out the workspace and/or deleting the file each run? Generally our build scripts do something like:

```bash
LINT_FILE=".phabricator-lint"
rm -f ${LINT_FILE}
<command that lints> | tee -a ${LINT_FILE}
<more commands>
```

**Comment by aadis** [comment]
Yes, it's being cleaned and regenerated.

**Comment by sectioneight** [comment]
Interesting. Are you sure? I can't think of any other reason you'd see lint errors other than it not being cleaned up. Can you add a `cat .phabricator-lint` to the beginning and end of your build script?

**Comment by aadis** [comment]
Ok, false alarm, sorry 😁
