### ISSUE TITLE
Harbormaster build results in 404 when tried to trigger Jenkins URI

### ISSUE THREAD

**Issue by blackshrub** [uber/phabricator-jenkins-plugin#202]
Harbormaster build step: Make HTTP Request
URI: https://my.ci.example/buildByToken/buildWithParameters?job=my-project-name&DIFF_ID=${buildable.diff}&PHID=${target.phid}&token=secret

Result:
Jenkins didn't give any responses, build failed with 404
![screen shot 2017-02-02 at 12 15 58 am](https://cloud.githubusercontent.com/assets/12421725/22517926/60c5ff12-e8dd-11e6-9788-bae46f0df52f.jpg)

I tried to do "Build with Parameters" in Jenkins by filling DIFF_ID and PHID manually from the failed build and it worked.

I'm not sure, but seems like something wrong with the URI.

**Comment by blackshrub** [comment]
In Jenkins job, navigate to "Build Triggers" --> "Trigger builds remotely" --> insert the token
Problem solved

**Comment by sectioneight** [comment]
Is there anything we could do to help clarify this in the documentation?

**Comment by samsun387** [comment]
It would be nice if this can be clarify in the jenkins section in https://github.com/uber/phabricator-jenkins-plugin#jenkins-job. I ran into this issue too.

**Comment by ansiz** [comment]
> In Jenkins job, navigate to "Build Triggers" --> "Trigger builds remotely" --> insert the token
> Problem solved


also make sure "Build Authorization Token Root" plugin has installed in Jenkins

**Comment by kwisatz** [comment]
> > In Jenkins job, navigate to "Build Triggers" --> "Trigger builds remotely" --> insert the token
> > Problem solved
> 
> also make sure "Build Authorization Token Root" plugin has installed in Jenkins

Shouldn't that bit of information be part of the README? Yes, I can submit a PR, but I'm astonished nobody has done so before.
