### ISSUE TITLE
JSON Example: Add Maniphest Tasks Comment.

### ISSUE THREAD

**Issue by OCram85** [uber/phabricator-jenkins-plugin#206]
Hi guys,
could you give me an example of your JSON string used to add the maniphest comment?

**Comment by sectioneight** [comment]
Can you clarify what you're looking for?

**Comment by OCram85** [comment]
I'm automating some stuff in phabricator and need to add a comment to an existing tasks.
Therefore I would like to use the conduit method `maniphest.edit` like you did. But I've got a little bit confused reading the [help](https://phabricator.kivbf-cloud.net/conduit/method/maniphest.edit/) .

So I'm searching for an JSON syntax example.

**Comment by artms** [comment]
Phabricator jenkins plugin is not working with maniphests directly... You should seek help in official Phabricator forum/IRC...
