### ISSUE TITLE
Plugin isn't compatible with Custom Tools

### ISSUE THREAD

**Issue by joshuaspence** [uber/phabricator-jenkins-plugin#21]
This is similar to #19... it seems that this plugin isn't compatible with the Custom Tools plugin.

I have the Custom Tools plugin configured as follows:

![tools](https://cloud.githubusercontent.com/assets/234676/7999884/60195c60-0b96-11e5-9752-e87748b0bd95.png)

The output from the job is as follows:

```
00:00:00.001 [EnvInject] - Inject global passwords.
00:00:00.002 Started by remote host 10.182.88.66
00:00:00.002 [CustomTools] - arcanist: Starting installation
00:00:00.009 [arcanist] $ sh -e /mnt/jenkins-slave-workspace/tools/com.cloudbees.jenkins.plugins.customtools.CustomTool/arcanist/hudson8373437206605157068.sh
00:00:00.023 [CustomTools] - arcanist: Tool is installed at /mnt/jenkins-slave-workspace/tools/com.cloudbees.jenkins.plugins.customtools.CustomTool/arcanist
00:00:00.023 [CustomTools] - arcanist: Setting arcanist_HOME=/mnt/jenkins-slave-workspace/tools/com.cloudbees.jenkins.plugins.customtools.CustomTool/arcanist
00:00:00.023 [EnvInject] - Loading node environment variables.
...
00:00:00.623 [redacted] $ sh -c 'echo '{"ids":["558494"]}' | arc call-conduit differential.querydiffs'
00:00:01.033 Applying patch for differential
00:00:01.036 [redacted] $ sh -c 'echo '{"silent":true,"action":"none","message":"Build started: https://redacted/job/redacted/19/ (console: https://redacted/job/redacted/19/console)","revision_id":"20969"}' | arc call-conduit differential.createcomment'
00:00:01.569 [redacted] $ git reset --hard origin/master
00:00:01.579 HEAD is now at 02a3a6c chore(build): bump version
00:00:01.585 [redacted] $ git clean -fd -f
00:00:01.597 [redacted] $ git submodule update --init --recursive
00:00:01.661 [redacted] $ arc patch --nobranch --diff 558494 --nocommit
00:00:01.663 FATAL: Cannot run program "arc" (in directory "/mnt/jenkins-slave-workspace/workspace/redacted"): error=2, No such file or directory
00:00:01.664 java.io.IOException: Cannot run program "arc" (in directory "/mnt/jenkins-slave-workspace/workspace/redacted"): error=2, No such file or directory
00:00:01.664    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
00:00:01.664    at hudson.Proc$LocalProc.<init>(Proc.java:244)
00:00:01.664    at hudson.Proc$LocalProc.<init>(Proc.java:216)
00:00:01.664    at hudson.Launcher$LocalLauncher.launch(Launcher.java:816)
00:00:01.664    at hudson.Launcher$ProcStarter.start(Launcher.java:382)
00:00:01.664    at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1149)
00:00:01.664    at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1114)
00:00:01.664    at hudson.remoting.UserRequest.perform(UserRequest.java:121)
00:00:01.664    at hudson.remoting.UserRequest.perform(UserRequest.java:49)
00:00:01.664    at hudson.remoting.Request$2.run(Request.java:324)
00:00:01.664    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
00:00:01.664    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:00:01.664    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
00:00:01.664    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
00:00:01.664    at hudson.remoting.Engine$1$1.run(Engine.java:63)
00:00:01.664    at java.lang.Thread.run(Thread.java:745)
00:00:01.664    at ......remote call to i-b7ea994a-ef4326cf(Native Method)
00:00:01.664    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1361)
00:00:01.664    at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
00:00:01.664    at hudson.remoting.Channel.call(Channel.java:753)
00:00:01.664    at hudson.Launcher$RemoteLauncher.launch(Launcher.java:929)
00:00:01.664    at com.cloudbees.jenkins.plugins.customtools.CustomToolInstallWrapper$2.launch(CustomToolInstallWrapper.java:255)
00:00:01.664    at hudson.Launcher$ProcStarter.start(Launcher.java:382)
00:00:01.664    at hudson.Launcher$ProcStarter.join(Launcher.java:389)
00:00:01.664    at com.uber.jenkins.phabricator.PhabricatorBuildWrapper.setUp(PhabricatorBuildWrapper.java:120)
00:00:01.664    at hudson.model.Build$BuildExecution.doRun(Build.java:156)
00:00:01.664    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
00:00:01.664    at hudson.model.Run.execute(Run.java:1744)
00:00:01.664    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
00:00:01.664    at hudson.model.ResourceController.execute(ResourceController.java:98)
00:00:01.664    at hudson.model.Executor.run(Executor.java:374)
00:00:01.665 Caused by: java.io.IOException: error=2, No such file or directory
00:00:01.665    at java.lang.UNIXProcess.forkAndExec(Native Method)
00:00:01.665    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
00:00:01.665    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
00:00:01.665    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
00:00:01.665    at hudson.Proc$LocalProc.<init>(Proc.java:244)
00:00:01.665    at hudson.Proc$LocalProc.<init>(Proc.java:216)
00:00:01.665    at hudson.Launcher$LocalLauncher.launch(Launcher.java:816)
00:00:01.665    at hudson.Launcher$ProcStarter.start(Launcher.java:382)
00:00:01.665    at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1149)
00:00:01.665    at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1114)
00:00:01.665    at hudson.remoting.UserRequest.perform(UserRequest.java:121)
00:00:01.665    at hudson.remoting.UserRequest.perform(UserRequest.java:49)
00:00:01.665    at hudson.remoting.Request$2.run(Request.java:324)
00:00:01.665    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
00:00:01.665    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:00:01.665    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
00:00:01.665    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
00:00:01.665    at hudson.remoting.Engine$1$1.run(Engine.java:63)
00:00:01.665    at java.lang.Thread.run(Thread.java:745)
```

**Comment by sectioneight** [comment]
Interesting. I haven't used the plugin before, but it looks like it's supposed to be adding the "exported path" into your path... Will try and repro later today.

**Comment by sectioneight** [comment]
I can repro the issue, but can't seem to extract the environment variables from the Custom Tools  plugin into my build wrapper. As a workaround (and necessary for the other issue) I can add a custom PATH to look for arc in, but I am still hoping to figure out a way to make this one work more seamlessly. In other words, `echo $PATH` during the build step works fine, but `PATH` isn't overridden at the time the differential is being applied.

**Comment by sectioneight** [comment]
I got this to work with #23 by configuring the custom tools like so:

![image](https://cloud.githubusercontent.com/assets/97087/8017591/f4ba7026-0bae-11e5-8538-b036f09b7765.png)

Does this seem like a reasonable tradeoff, or can you think of a better way for the tools to work together (e.g. try to install arcanist/phutil by default)

**Comment by joshuaspence** [comment]
In the short term, I think this is fine. In the long term, it feels clunky (it is sort of tied to the implementation of Custom Tools).

Alternatively, we could have this plugin just install arcanist/libphutil itself. That way, I don't need to use the Custom Tools plugin for this purpose.

**Comment by sectioneight** [comment]
Ok, so here's what I'm thinking:

Merge this PR as-is, since this solves #19.

Next, we add a step that attempts to auto-install (and update?) arcanist and libphutil if none is found in the system path and no custom path is configured.

@jjx what do you think? (also @joshuaspence: are there other phab contributors that would like access to this repo? i don't intend to be the gatekeeper, just trying to contribute back the work we've done at uber to make CI seamless (which for us, involves puppetizing a ~/.arcrc for jenkins slaves and cloning arcanist into a path that gets sets into bin, which I'm now realizing is not something most people want to be doing).

Thanks for all the suggestions1

**Comment by joshuaspence** [comment]
+1. Yes, an option to auto-update would be appreciated (I like to live on the bleeding edge).

I don't know of any other Phabricator contributors that even use Jenkins to be honest.

Yeah, I was considering puppetizing the `~/.arcrc` and arcanist installation... but I prefer to do this within CI itself. It simplifies our puppet manifests and means that we only install tools such as arcanist on slaves which actually need them. Furthermore, it makes it possible for us to run different versions of these tools if we need to (as opposed to installing a single version globally).

**Comment by lavahot** [comment]
@joshuaspence Oh, Custom Tool. I've never heard of it. That's cool. That would probably solve #19 if I can set it up correctly.

**Comment by lavahot** [comment]
> Next, we add a step that attempts to auto-install (and update?) arcanist and libphutil if none is found in > the system path and no custom path is configured.

@sectioneight As far as installation goes, since there are numerous installation methods for several package manager repos (albeit in "unstable"), installation when arcanist is not found should be a checkbox, not default behavior.

**Comment by sectioneight** [comment]
This isn't really fixed yet

**Comment by sectioneight** [comment]
I think the direction we're going, now that Harbormaster HTTP is being used (as opposed to arc call-conduit) and Staging repos are available, is to encourage people away from the "arc patch" ("Apply Phabricator Differential") step, which means we no longer have to have `arc` installed on any of the jenkins nodes.

Does this approach seem reasonable @joshuaspence, or would you prefer to simultaneously pursue a solution where we install/upgrade arcanist for the `arc patch` step?

**Comment by sectioneight** [comment]
Closing for now, let me know if you'd like to continue investigating alternative auto-upgrade-arcanist strategies.
