### ISSUE TITLE
Unable to make POST request to jenkins - status 400

### ISSUE THREAD

**Issue by Chhayak74** [uber/phabricator-jenkins-plugin#217]
Harbormaster build log says -

<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
<br></br>

On opening the link below, build starts successfully-
https://f5361d02.ngrok.io/job/v3 test/buildWithParameters?job=v3 test&PHID=PHID-HMBT-6ewovqeovgbpq4cfimpj&DIFF_ID=209&token=PHID-CDTL-shhug7eqi5m65k3hyssb

But the build is not being triggered on its own.(Although I have applied the authentication token in the jenkins configuration)

**Comment by riteshshrv** [comment]
@Chhayak74 I too ran into the same problem, did you find any solution to this?

**Comment by Chhayak74** [comment]
@riteshshrv I missed out on installing 'Build Token Root Plugin'. After installing it, everything is working perfectly.
