### ISSUE TITLE
HTTP/S Mixed content issue when trying to add phabricator credentials

### ISSUE THREAD

**Issue by Myz** [uber/phabricator-jenkins-plugin#232]
Requesting http from https context might be a bad idea with modern web browsers. They first started to complain about it and now they are blocking the request completely:

This for example is coming from google-chrome version 60.0.3112.101 (Official Build) (64-bit):

```
Mixed Content: The page at 'https://example.org/configure' was loaded over HTTPS, but requested an insecure form action 'http://example.org/descriptor/com.cloudbees.plugins.credentials.CredentialsSelectHelper/resolver/com.cloudbees.plugins.credentials.CredentialsSelectHelper$SystemContextResolver/provider/com.cloudbees.plugins.credentials.SystemCredentialsProvider$ProviderImpl/context/jenkins/addCredentials'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by artms** [comment]
Please give how to reproduce, it looks like your jenkins instance is properly configured to use https and leaks http:// in some places...

**Comment by Myz** [comment]
Found and solved a problem in the configuration of the http webserver used as an frontend to the jenkins instance.

Works now like expected.
