### ISSUE TITLE
Conduit Credentials kind missing

### ISSUE THREAD

**Issue by anitakrueger** [uber/phabricator-jenkins-plugin#239]
I've installed the phabricator plugin and when trying to add a new conduit credential, the phabricator credential type is not showing up in my list of kinds of creds. All I have in there is:
- username with password
- ssh username with private key
- secret file
- secret text
- certificate
And two more.

I am not sure what to look for in the logs, but it looks like the plugin was installed successfully, as I can find the configuration paragraph for phabricator under Manage Jenkins.

Any pointers would be great. Thanks!

**Comment by artms** [comment]
What version of Jenkins do you use? Also try restarting jenkins if it was not restarted after plugin installation maybe some hook failed and it might register conduit credential type on restart...

**Comment by anitakrueger** [comment]
@artms We are running jenkins 2.68 and it has been restarted several times after installing the plugin.
Is there any way I can turn on debugging to see what's going on? Or does the plugin have any other prerequisites that I may be missing?
Thanks for your help!

**Comment by artms** [comment]
Unfortunately we use old Jenkins and didn't test plugin with 2.68... Maybe somebody else in community used plugin with newer plugin and can report if it has issues with credentials...

**Comment by anitakrueger** [comment]
@artms which Jenkins version do you use then? As far as I can see, the docs say the dependency is Credentials 1.22. We have 2.1.16.

If you can tell how to turn on debugging for the plugin, may be I can do some digging myself. I'm a bit lost.

**Comment by artms** [comment]
We use 2.1.13 credentials plugin, unfortunately we do not use 2.68 jenkins at the moment and I can't check how it behaves, we only plan upgrading jenkins next year. Do you use plugin which is available in jenkins official plugin repository or building it locally? 0.9.8 plugin is quite old and there were some issues uploading new version of plugin since then and generally it is best to use one which is built from master branch...

**Comment by anitakrueger** [comment]
@artms we have 1.9.7 installed which came from the jenkins repo's.

However, I found the issue. In jenkins 2.68 you can explicitly configure credential types to be enabled or not.
Under "Manage Jenkins" -> "Configure Credentials" there is an option to only enable selected types of credentials. And the "Phabricator Conduit Key" wasn't enabled in there. I feel a bit embarrassed, not seeing this earlier.

**Comment by artms** [comment]
Thanks for report, we'll update Readme to include that step!
