### ISSUE TITLE
Using Jenkins Git Credentials for git submodules

### ISSUE THREAD

**Issue by karthiksrinivasan** [uber/phabricator-jenkins-plugin#258]
Hi,

Thanks for providing us with the plugin to integrate Jenkins system with Phabricator.

We are currently running into an issue when the differential from phabricator contains changes to .gitmodules file in the repository. The phabricator plugin attempts to run 'git submodules` without considering the credentials used for prior git operations. Therefore, this is causing the builds with .gitmodules change to fail due to submodules update fail with the permissions error.

Any insight into how to tackle this problem will be helpful and greatly appreciated.

Regards,
Karthik

**Comment by arcadien** [comment]
Hi,
You can fix this in the job setup:
![image](https://user-images.githubusercontent.com/1871319/63005176-49822980-be7c-11e9-9eca-e3841c625255.png)

**Comment by artms** [comment]
Issue unrelated to plugin itself
