### ISSUE TITLE
Arc diff on ecs container gives exception

### ISSUE THREAD

**Issue by C2L2C** [uber/phabricator-jenkins-plugin#264]
On diff creation, jenkins gets triggered and tries to run the build on an AWS ECS container. I am getting the following error(console output):

[phabricator:conduit] Fetching differential from Conduit API
[PhTest] $ **** reset --hard dd6a90f456ac737e7e667e5278a033f3a12c72dc
fatal: Not a **** repository (or any of the parent directories): .****
[phabricator:arc-patch] Got non-zero exit code resetting to base commit dd6a90f456ac737e7e667e5278a033f3a12c72dc: 128
[PhTest] $ **** clean -fd -f
fatal: Not a **** repository (or any of the parent directories): .****
[PhTest] $ **** submodule update --init --recursive
fatal: Not a **** repository (or any of the parent directories): .****
[PhTest] $ /tmp/arcanist/bin/arc patch --diff 1179 --nocommit --nobranch --force ********
****[1mUsage Exception:[m `arc patch` is only supported under ****, hg, svn.****

After which the build is marked failed. Can anyone point out what am I doing wrong?

**Comment by artms** [comment]
Not related to plugin itself, you didn't properly checkout repository or it is not git/mercurial based one
