### ISSUE TITLE
Link to differential is broken

### ISSUE THREAD

**Issue by lavahot** [uber/phabricator-jenkins-plugin#27]
The current links on Jenkins to differentials is domain.comd1, not domain.com/D1. Using v1.2.

**Comment by sectioneight** [comment]
Depends on how you have your phab url configured. We should be smarter and
insert a slash if necessary.

**Comment by lavahot** [comment]
But it's not just the slash, the D has to be capitalized too.

**Comment by sectioneight** [comment]
Interesting. This works properly at Uber. I'll dig in tomorrow. Thanks for
the report.

**Comment by sectioneight** [comment]
Just wondering -- where are you seeing this? The only code path I see that puts a "D" anywhere is here:

https://github.com/uber/phabricator-jenkins-plugin/blob/9fd0f873645815e89553ec88d3f3ac9ad254d45c/src/main/java/com/uber/jenkins/phabricator/conduit/Differential.java#L58-L60

**Comment by sectioneight** [comment]
@lavahot can you provide me with a screenshot/log of where exactly you're seeing this lowercase "d" so I can debug?

**Comment by lavahot** [comment]
The two places I've noticed this is on the build page and in the build history widget.  
![screenshot from 2015-06-07 14 37 52](https://cloud.githubusercontent.com/assets/962444/8026225/2f495d4a-0d23-11e5-8d03-bce0b0a22f0d.png)
![screenshot from 2015-06-07 14 37 38](https://cloud.githubusercontent.com/assets/962444/8026226/2f4b125c-0d23-11e5-82d3-2a00705e710b.png)

You can't see my mouse cursor in either of these (thanks Ubuntu), but they are hovering over the D1 links. You can see Chrome show the link addresses in the bottom left corner.

**Comment by sectioneight** [comment]
ok, so the capitalization is correct, but the links themselves are
malformed? mind reviewing the linked PR

**Comment by sectioneight** [comment]
#29

**Comment by lavahot** [comment]
OH, yes, the text is correct, but the url is bad. Sorry, I thought that was clear.

**Comment by sectioneight** [comment]
Fixed by #29
