### ISSUE TITLE
Release 2.1.2

### ISSUE THREAD

**Issue by AttwellBrian** [uber/phabricator-jenkins-plugin#318]
Noticed that the fix for #296 #312 hasn't been released since it was landed in December. Any chance of cutting a new release and deploying it to the jenkins plugin repo?

**Comment by vitorhugods** [comment]
Yeeeah, that would be great.
The #296 is really annoying.

**Comment by pasikarkkainen** [comment]
New release: yes please :)

**Comment by vj396** [comment]
new release, yes please :), #296 is definitely annoying.

**Comment by pasikarkkainen** [comment]
Any chance for a new release?

**Comment by pasikarkkainen** [comment]
Actually, it seems v2.1.2 was already released! So this issue can be closed.
