### ISSUE TITLE
How to report Unit Test/Coverage Data?

### ISSUE THREAD

**Issue by korroktheslavemaster** [uber/phabricator-jenkins-plugin#321]
I couldn't find any documentation stating what file names are scanned for reporting unit test or coverage related information. I have `junit.xml` and `coverage/cobertura-coverage.xml` generated in the workspace, but the output I get from this plugin is
```
[Cobertura] Publishing Cobertura coverage report...

[Cobertura] Publishing Cobertura coverage results...

[Cobertura] Cobertura coverage report found.

[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /home/jenkins/workspace/workspace/mapcreator-unit to /var/lib/jenkins/jobs/mapcreator-unit/htmlreports/HTML_20Report
[phabricator:uberalls] Using coverage metrics from Cobertura Jenkins Plugin
[phabricator:process-build-result] No Uberalls backend configured, skipping...
[phabricator:process-build-result] No unit results available.
[phabricator:process-build-result] No line coverage available to post to Harbormaster.
[phabricator:harbormaster] Sending Harbormaster BUILD_URL via PHID: PHID-HMBT-b6hpvcmli4jphxjig5si
[phabricator:send-harbormaster-uri] Harbormaster declined URI artifact: #1062: Duplicate entry 'uri-HWtZugQhmf51' for key 'key_artifact'
[phabricator:process-build-result] Unable to send BUILD_URL to Harbormaster. This can be safely ignored, and is usually because it's already set.
[phabricator:process-build-result] Sending build result to Harbormaster with PHID PHID-HMBT-b6hpvcmli4jphxjig5si, success: true
[phabricator:file-fetcher] no files found by path: '.phabricator-comment'
Finished: SUCCESS
```

**Comment by zstyblik** [comment]
I believe it's described in `readme.md`:

> 2. If you want to post additional text to Phabricator other than "Pass" and "Fail", select the Add Custom Comment checkbox. Then create a .phabricator-comment file and enter the text you want Jenkins to add to the build status comment in Phabricator.

**Comment by korroktheslavemaster** [comment]
The text in `.phabricator-comment` is just posted as a comment in phab. What I want is formatted unit/coverage reports. The following lines are printed in jenkins (as i said earlier also)
```
[phabricator:process-build-result] No Uberalls backend configured, skipping...
[phabricator:process-build-result] No unit results available.
[phabricator:process-build-result] No line coverage available to post to Harbormaster.
```
To me this indicates that there are some special mechanisms for detecting and publishing unit results and coverage reports built into this plugin. However I wasn't able to find any source for how to do this.
