### ISSUE TITLE
Add option for skipping Harbormaster messages

### ISSUE THREAD

**Issue by KevinGrandon** [uber/phabricator-jenkins-plugin#322]
**Use case:**

We have a multijob which reports back to Phabricator. We can't use this plugin for individual sub-jobs, otherwise they would clobber the status of the multijob before the multijob is done. We want the multijob status reported back to the differential revision.

We want to use the phabricator plugin for sub-job diff patching without status updates, and for multijob status reporting.

**Possible user implementation:**
```
<com.uber.jenkins.phabricator.PhabricatorBuildWrapper plugin="phabricator-plugin@1.9.5">
  <skipHarbormasterMessages>true</skipHarbormasterMessages>
</com.uber.jenkins.phabricator.PhabricatorBuildWrapper>
```

**Comment by kageiit** [comment]
The plugin allows patching without reporting to harbormaster. The patching step is different from the publication step so you can have the sub jobs do the patching only and chose not to report status back. You can report status back on the multijob then

**Comment by artms** [comment]
I suppose #340 will solve it, though I think issue is no longer relevant
