### ISSUE TITLE
How to create Conduit API token for bot user?

### ISSUE THREAD

**Issue by fangwei18** [uber/phabricator-jenkins-plugin#327]
I create a bot user named jenkins in phabricator, but when I tried to set its password
```
./bin/auth recover jenkins
```
I got this
```
Usage Exception: This account ("jenkins") can not establish web sessions, so it is not possible to generate a functional recovery link. Special accounts like daemons and mailing lists can not log in via the web UI.
```
So how can I create Conduit API token for jenkins when it cannot log in via web UI?

**Comment by girtsf** [comment]
As administrator you can go to your bot user, click "Manage", "Edit Settings", "Conduit API Tokens".

**Comment by CadenOf** [comment]
you can login with your admin account, then "Edit Settings" > "Conduit API Tokens", 
now your url will like `https://xxx.phabricator.xx.com/settings/user/${your_admin_account}/page/apitokens/`
replace ${your_admin_account} with ${your_bot_user_name}, such as 
`https://xxx.phabricator.xx.com/settings/user/${your_bot_user_name}/page/apitokens/`
click `return`, then you can see it.

**Comment by zkhkoku** [comment]
thx!

**Comment by artms** [comment]
Issue unrelated to plugin itself
