### ISSUE TITLE
Selecting --output json suppresses errors in the configuration

### ISSUE THREAD

**Issue by cg-soft** [uber/phabricator-jenkins-plugin#335]
A syntax error in a wrapper script run by arc will generate a visible error, like so:

    Exception
    Some linters failed
        - CommandException: Command failed with error ##2
          COMMAND
          '<shell-script>'
          STDOUT
          [empty]
          STDERR
          <shell-script>: line 10: syntax error near unexpected token

Running the same command with `--output json` totally suppresses this error, rendering it undetectable.

**Comment by artms** [comment]
Doesn't seem to be related to plugin itself, report issue to arcanist upstream https://secure.phabricator.com/
