### ISSUE TITLE
Option to post partial updates and omit pass/fail

### ISSUE THREAD

**Issue by sman591** [uber/phabricator-jenkins-plugin#341]
I'm working with a Phabricator <-> Jenkins setup where we have one "root" job that kicks off several "child" jobs.

We'd like the ability for all of these jobs to independently report **partial** updates (e.g. unit/lint/coverage results) but **not** set the pass/fail status while doing so. Only the root job should set a pass/fail status; child jobs merely provide supporting content & comments.

Example timeline with this workflow:

```
1. Root job is triggered (by Harbormaster)
    --> Root job starts child job A
    --> Root job starts child job B
2. Child job A passes, posts lint & coverage reports
3. Child job B fails, posts a comment
4. Root job notified other jobs are done, job B failed, and posts a "fail" status
```

### One proposed solution

Looking at Harbormaster's `sendMessage` API, it seems like reporting a `work` type with these unit/lint/etc updates would be appropriate for this use case, rather than the `pass` or `fail` type this plugin uses today.

<img width="871" alt="Screen Shot 2020-04-08 at 12 27 34 PM" src="https://user-images.githubusercontent.com/1441807/78825152-5536d900-7994-11ea-85b0-083137f4435e.png">

In addition to checkboxes/parameters such as "Comment on Success", we add an additional checkbox (e.g. "Don't set pass/fail status"). When enabled, this plugin will send a `work` type rather than `pass` or `fail`.

For reference, it looks like this is one key point where this status type is set:

https://github.com/uber/phabricator-jenkins-plugin/blob/3774712e62dc48a7eed82293755828c93fd862a5/src/main/java/com/uber/jenkins/phabricator/conduit/HarbormasterClient.java#L61

Would something like this make sense? If implemented, would this be an acceptable contribution?

**Comment by artms** [comment]
If code change itself would not be large then it would be acceptable.

**Comment by pasikarkkainen** [comment]
Sounds good and useful to me!

**Comment by gregmagolan** [comment]
@artms @pasikarkkainen @sman591 I put up https://github.com/uber/phabricator-jenkins-plugin/pull/346. PTAL
