### ISSUE TITLE
[Question] Is it possible to add custom phabricator comment from a jenkins pipeline step?

### ISSUE THREAD

**Issue by OCram85** [uber/phabricator-jenkins-plugin#343]
Hey guys,
Is it possible to provide such a file like described in the [Advanced usage docs](https://github.com/uber/phabricator-jenkins-plugin/blob/master/docs/advanced.md#custom-comments) from a jenkins pipeline?

I've already figured out how to use the `PhabricatorNotifier` itself, but couldn't find anything about the custom comments:

```
...
post {
  always {
    script {
      currentBuild.result = currentBuild.currentResult
    }
    step([$class: 'PhabricatorNotifier', commentOnSuccess: true, commentWithConsoleLinkOnFailure: true])
  }
}
```

**Comment by artms** [comment]
Unfortunately Uber is not using Jenkins Pipelines and we have no experience nor need for this, maybe somebody else tried and can comment

**Comment by OCram85** [comment]
Thanks for the reply.
After reading #185 I hoped someone already tried this. Maybe @balihb could help 😸

**Comment by balihb** [comment]
the default comment file name is defined here:
https://github.com/uber/phabricator-jenkins-plugin/blob/eff89b3697bf06cffb68f8b9fe9c9c41c1575a72/src/main/resources/com/uber/jenkins/phabricator/PhabricatorNotifier/config.jelly#L44

**Comment by OCram85** [comment]
@balihb: So by providing a `.phabricator-comment` as pipeline step, the notifier will automatically add the content?

**Comment by balihb** [comment]
not a step. as a file. it pick it up by default. you can use the
phabricator markup language in the file.

**Comment by OCram85** [comment]
Awesome, didn't noticed the `PhabricatorNotifier` class uses the existing `.phabricator-comment` file 😄

**Comment by OCram85** [comment]
@balihb: For testing I added a static `.phabricator-comment` file. Unfortunately it wasn't attached. Do I have to customize the post step other than this:

```
 post {
    always {
      script {
        currentBuild.result = currentBuild.currentResult
      }
      step([$class: 'PhabricatorNotifier', commentOnSuccess: true, commentWithConsoleLinkOnFailure: true])
    }
  }
```

**Comment by jhimy-michel** [comment]
where does the .phabricator-comment file has to be added? inside jenkins or phabricator?

**Comment by OCram85** [comment]
I ended up using the Phabricator API itself to add custom comments:

```groovy
stage('.phabircator-comment') {
  steps {
    sh label: 'Reporting results', script: 'curl https://phabricator.foo.bar/api/differential.createcomment -d api.token=$MYAPIKEY -d revision_id=$ABORT_ON_REVISION_ID -d message="$(cat .phabricator-comment)"'
}


```

**Comment by OCram85** [comment]
> Just solved this with workaround shown in  [previous comment](https://github.com/uber/phabricator-jenkins-plugin/issues/343#issuecomment-664166677) 😃
