### ISSUE TITLE
Release v2.1.4 ?

### ISSUE THREAD

**Issue by pasikarkkainen** [uber/phabricator-jenkins-plugin#347]
Hello! I'd be nice to have a new release (2.1.4) with the latest commits included. Thanks!

**Comment by pasikarkkainen** [comment]
gentle ping :) @kageiit

**Comment by kageiit** [comment]
cc @artms

**Comment by pasikarkkainen** [comment]
ping @artms @kageiit :) any chance for a new release?

**Comment by artms** [comment]
Trying to release then

**Comment by artms** [comment]
https://github.com/uber/phabricator-jenkins-plugin/pull/350

**Comment by artms** [comment]
Release 2.1.5 version (skipped 2.1.4 due to mistake I made in release commit)
