### ISSUE TITLE
Remove blocking reviewer (leave) from review on success

### ISSUE THREAD

**Issue by sogwiz** [uber/phabricator-jenkins-plugin#36]
I currently have a Herald rule that sets my Jenkins build bot user as a Mandatory blocking Reviewer.  After phabricator executes the build plan via jenkins, is there a way to automatically remove the Mandatory Review from the review if the build succeeds?

Sequence:
1. Herald rule to add Jenkins build bot user as mandatory reviewer
2. Herald rule to execute build plan
3. Jenkins runs build and reports back to phabricator via comment
4. FEATURE REQUEST: could there be a way for the mandatory Jenkins reviewer to leave the review if the build succeeds?

Thank you :)

**Comment by sectioneight** [comment]
This is an interesting one. Have you looked at Harbormaster? It may be a better fit, although I understand wanting to have the "blocking" review.

In your current system, do you have jenkins "resigning" or "accepting" the review when the build finishes?

**Comment by sogwiz** [comment]
Thanks for the quick reply @sectioneight ! 

In response to your question: "do you have jenkins "resigning" or "accepting" the review when the build finishes?"...

I simply have jenkins leave a comment. I didn't know I could get it to "resign" or "accept" automatically. Do you know how to configure this? My preference would be to have it "resign" automatically only if the build fails. I'd rather not jenkins "accept" the review to avoid a false positive.

**Comment by sectioneight** [comment]
"resigning" means removing your blocking review -- it removes jenkins from the list of reviewers. You can pass an "action" field when making a comment, but you'd only want to resign in the case of a *successful* build, and "request changes" when the build fails.

https://github.com/uber/phabricator-jenkins-plugin/blob/master/src/main/java/com/uber/jenkins/phabricator/PhabricatorNotifier.java#L179-L184

https://github.com/uber/phabricator-jenkins-plugin/blob/a93cfd88ca5921df0e84229e628daf120688b502/src/main/java/com/uber/jenkins/phabricator/conduit/Differential.java#L117-L125

So you could probably make it work with your current flow ("resign" on success), but this may be something we want to include in the plugin if it makes sense for other people.

**Comment by sogwiz** [comment]
Thanks.  Can you please point me to the syntax / format of the comment file? Looks like an interesting approach

**Comment by sectioneight** [comment]
We may be talking about two different things. 1) is that I think you can accomplish this with your current flow without this plugin, just adding a "resign" action when your build finishes as it's currently commenting.

The 2) approach is using the plugin, and not having a blocking review, but using the harbormaster status (`arc` will warn you if you try to land an in-progress build or the build has failed). The comment file is just plain text.

**Comment by sogwiz** [comment]
One final question for ya :) 

When you state, "just adding a "resign" action when your build finishes as it's currently commenting.", how exactly do I do this? I don't see somewhere in the plugin options to allow for this. I also don't see the resign action in either my Harold or Harbormaster options (perhaps I have an older version)

**Comment by sectioneight** [comment]
It is not an option that the plugin currently has configurable.

However, if you launch a build without a PHID parameter, it will assume harbormaster integration is disabled and that's the code I was pointing to. If the build fails, jenkins will "request changes", and when it succeeds he will "resign" to remove the blocking reviewer.

I'm not totally clear on your current flow, but if you're posting comments manually (via arc call-conduit) then it's as simple as adding an `action` key to the JSON blob.

**Comment by sectioneight** [comment]
Any more thoughts on this one, or should I close it out?

**Comment by tayalakansh** [comment]
Hi,

Is this feature request taken care of? I am having a similar use case in which Jenkins bot is added as a blocking reviewer but it doesn't accept the review even if jenkins build passes.

Looking for a way to make blocking reviewer accept the review if build in jenkins passes.
