### ISSUE TITLE
Additional comments without code blocks

### ISSUE THREAD

**Issue by d-claassen** [uber/phabricator-jenkins-plugin#75]
Would it be possible to submit the contents of `.phabricator-comment` to Phabricator without the surrounding code block?

We use a lot of custom styling in our messages, that we are currently sending with a Groovy Postbuild script. Because of the code block, we lose all of our styling. We would like to use the phabricator comment file, because currently we need to set up the entire communication with Phabricator ourselves, which is unnecessary when this plugins provides that exact functionality.

I'll be able to submit a pull request, but wanted to check if this fix is something you're willing to accept.

**Comment by sectioneight** [comment]
That seems very reasonable. Let's just make it configurable via the
descriptor.

**Comment by sectioneight** [comment]
@d-claassen were you going to submit a PR or would you like me to implement?

**Comment by d-claassen** [comment]
I would have no idea how to make it configurable. I think it'll be done a lot better when you would implement it ;-)

**Comment by sectioneight** [comment]
Sounds good. I will add a checkbox to "preserve formatting" that you can enable.

**Comment by sectioneight** [comment]
This is in master, will be released in 1.8.0 (hopefully this week)

**Comment by d-claassen** [comment]
Nice! Already using it. Thanks for the quick implementation
