### ISSUE TITLE
Jenkins Job Builder Support

### ISSUE THREAD

**Issue by cburroughs** [uber/phabricator-jenkins-plugin#81]
http://docs.openstack.org/infra/jenkins-job-builder/

I'd like the plugin to support the jenkins job builder because manually configuring hundreds of jobs isn't fun.  Nothing needs to be done in the plugin code and I intend to go write up the patch myself and report back.  However, if someone was planning on introducing a bunch of backwards incompatible changes Real Soon that would be good to know.

**Comment by sectioneight** [comment]
Sweet.

This looks like a really cool tool. cc @Ignas have you seen the jenkins job builder?

No backwards incompatible changes are in the works as far as I know. I'm about to merge #79 which removes the need to have Cobertura installed just to use this plugin, but that's just an internal refactor.

**Comment by cburroughs** [comment]
https://review.openstack.org/#/c/215750/

**Comment by Erethon** [comment]
@cburroughs thank you for this, I was planning on doing it myself, but you beat me to it!

One question though -quoting your commit message-
```
NOTE: The plugin also provides a wrapper.  The future of that is
unclear time at this time so no jjb support is added.
```
I've searched the issues on this repo and didn't find any reference on the
wrapper being a WIP/unclear feature. Care to explain this a bit furter?

Once again, thank you for your work.

**Comment by cburroughs** [comment]
Upstream strongly recommends against the `arc patch` based approach (the better approaches did not exist when this plugin was first written).  I'm not sure it makes sense to encourage `arc patch` via the wrapper (It is recommended after all) but there is also very little cost to keeping it around for backwards compatibility while things shake out.

See https://secure.phabricator.com/book/phabricator/article/harbormaster/#change-handoff & https://secure.phabricator.com/T8090

**Comment by sectioneight** [comment]
I agree with your assessment. We'll probably support the wrapper
indefinitely given the migration cost of the job configurations and
harbormaster rules.

But most people should just need the notifier, which has the nice effect of
making this plugin SCM agnostic.

**Comment by sectioneight** [comment]
@cburroughs should we close this task, or is there more to do?
